spring:
  application:
    name: springcloud-server
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
  instance:
    prefer-ip-address: true
